# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.9

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
    -   id: add-trailing-comma
        name: Add trailing commas
        description: Automatically add trailing commas to calls and literals.
        entry: add-trailing-comma
        language: python
        types: [ python ]
-   repo: local
    hooks:
    -   id: system
        name: PyLint
        entry: poetry run pylint
        language: system
        exclude: ^alembic|tests/
        files: \.py$
        stages:
            - commit
#    -   id: system
#        name: PyTest
#        entry: poetry run pytest tests
#        language: system
#        pass_filenames: false
#        always_run: true
#        stages:
#            - commit
