"""Refactor

Revision ID: 780aee67ba88
Revises: 291c37b08074
Create Date: 2021-10-01 22:37:05.958544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780aee67ba88'
down_revision = '291c37b08074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
